
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Not dumping tablespaces as no INFORMATION_SCHEMA.FILES table on this server
--
DROP TABLE IF EXISTS `drupal_content_field_candidate_prcvd_qualities`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `drupal_content_field_candidate_prcvd_qualities` (
  `vid` int(10) unsigned NOT NULL default '0',
  `nid` int(10) unsigned NOT NULL default '0',
  `delta` int(10) unsigned NOT NULL default '0',
  `field_candidate_prcvd_qualities_value` longtext,
  PRIMARY KEY  (`vid`,`delta`),
  KEY `nid` (`nid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `drupal_content_field_candidate_prcvd_qualities` WRITE;
/*!40000 ALTER TABLE `drupal_content_field_candidate_prcvd_qualities` DISABLE KEYS */;
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2536,1665,1,'kreatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2412,1611,1,'chaotyczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2412,1611,0,'niecierpliwa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2435,1614,2,'racjonalistka');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2435,1614,1,'dynamiczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2435,1614,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2437,1615,2,'odpowiedzialna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2437,1615,1,'kompromisowa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2437,1615,0,'poukładana');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2439,1616,2,'otwarty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2439,1616,1,'odpowiedzialny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2439,1616,0,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2442,1618,2,'asertywność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2442,1618,1,'odpowiedzialność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2442,1618,0,'pracowitość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2444,1619,2,'zdecydowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2444,1619,1,'zorganizowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2444,1619,0,'szczery');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2446,1620,2,'pedantyczny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2446,1620,1,'cierpliwy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2446,1620,0,'odważny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2448,1621,2,'pewna siebie');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2448,1621,1,'towarzyska');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2448,1621,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2450,1622,2,'Zdystansowana');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2450,1622,1,'Punktualna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2450,1622,0,'Wytrwała');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2452,1623,2,'BŁYSKOTLIWA');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2452,1623,1,'STANOWCZA');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2452,1623,0,'AMBITNA');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2459,1629,2,'Zasadniczy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2459,1629,1,'Ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2459,1629,0,'Wymagający');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2464,1630,1,'odporność na stres ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2464,1630,0,'komunikatywność ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2470,1632,2,'łatwość przyswajania wiedzy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2470,1632,1,'dążenie do zaplanowanego celu');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2470,1632,0,'dokładność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2472,1633,2,'skrupulatna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2472,1633,1,'dokładna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2472,1633,0,'pracowita');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2572,1684,0,'odpowiedzialność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2572,1684,1,'opanowanie');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2570,1683,0,'odpowiedzialność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2570,1683,1,'opanowanie');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2544,1669,2,'rzetelna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2544,1669,1,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2544,1669,0,'otwarta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2548,1672,2,'kreatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2548,1672,1,'wytrwała');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2548,1672,0,'energiczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2550,1673,2,'myślący');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2550,1673,1,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2550,1673,0,'spokojny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2552,1674,2,'otwarta na świat i ludzi');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2552,1674,1,'pracowita');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2552,1674,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2554,1675,2,'energiczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2554,1675,1,'ciekawska');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2554,1675,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2556,1676,2,'otwarta na świat i ludzi');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2556,1676,1,'pracowita');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2556,1676,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2558,1677,2,'odpowiedzialność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2558,1677,1,'optymizm');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2558,1677,0,'logiczne myślenie');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2560,1678,2,'Racjonalny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2560,1678,1,'Dojrzały');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2560,1678,0,'Wpływowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2562,1679,1,'zaradny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2562,1679,0,'komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2564,1680,2,'twardo stąpający po ziemi');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2564,1680,1,'zaradny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2564,1680,0,'komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2566,1681,2,'odpowiedzialna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2566,1681,1,'skrupulatna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2566,1681,0,'kompetentna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2568,1682,1,'opanowanie');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2568,1682,0,'odpowiedzialność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2536,1665,0,'wytrawała');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2574,1685,2,'dbałość o relacje interpersonalne');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2574,1685,1,'ambicja');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2574,1685,0,'żywiołowość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2576,1686,2,'dbałość o relacje interpersonalne');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2576,1686,1,'ambicja');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2576,1686,0,'żywiołowość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2611,1689,2,'kreatywność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2611,1689,1,'poczucie humoru');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2611,1689,0,'odpowiedzialność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2615,1691,2,'Socjalny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2615,1691,1,'Ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2615,1691,0,'Zdeterminowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2618,1692,2,'pracowita');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2618,1692,1,'wierząca');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2618,1692,0,'rezolutna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2620,1693,2,'zorganizowana');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2620,1693,1,'socjalna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2620,1693,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2656,1701,2,'amibitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2656,1701,1,'radosny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2656,1701,0,'otwarty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2920,1739,2,'Konsekwentność, umiejętnośc planowania,  ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2920,1739,1,'Szczerość, pewność siebie, kreatywność ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2920,1739,0,'Terminowość,punktualność, cierpliwość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3145,1807,2,'Odpowiedzialny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3145,1807,1,'Kreatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3145,1807,0,'Komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3147,1808,2,'Odpowiedzialny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3147,1808,1,'Kreatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3147,1808,0,'Komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3153,1809,2,'c');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3153,1809,1,'b');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3153,1809,0,'a');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2572,1684,2,'optymizm');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2570,1683,2,'optymizm');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2568,1682,2,'optymizm');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2562,1679,2,NULL);
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2536,1665,2,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2464,1630,2,'dyscyplina');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (2412,1611,2,'szczera');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3203,1814,0,'1');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3203,1814,1,'2');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3203,1814,2,'3');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3207,1815,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3207,1815,1,'obowiązkowa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3207,1815,2,'uparta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3209,1816,0,'szczęśliwa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3209,1816,1,'radosna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3209,1816,2,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3212,1818,0,'optymistka');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3212,1818,1,'przebojowa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3212,1818,2,'komunikatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3214,1819,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3214,1819,1,'komunikatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3214,1819,2,'odpowiedzialna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3216,1820,0,'opanowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3216,1820,1,'zorganizowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3216,1820,2,'odpowiedzialny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3218,1821,0,'pracowitość ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3218,1821,1,NULL);
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3218,1821,2,NULL);
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3220,1822,0,'otwarta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3220,1822,1,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3220,1822,2,'optymistycznie nastawiona do życia');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3223,1824,0,'komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3223,1824,1,'bezpośredni');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3223,1824,2,'idealizujący');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3225,1825,0,'otwarty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3225,1825,1,'szczery');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3225,1825,2,'inteligentny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3227,1826,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3227,1826,1,'punktualna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3227,1826,2,'otwarta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3229,1827,0,'pracowita, kreatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3229,1827,1,'pozytywnie nastawienia do ludzi, komunikatywność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3229,1827,2,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3231,1828,0,'Komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3231,1828,1,'Punktualny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3231,1828,2,'Pracowity');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3233,1829,0,'Komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3233,1829,1,'Punktualny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3233,1829,2,'Pracowity');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3235,1830,0,'zorganizowana');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3235,1830,1,'sprytna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3235,1830,2,'uśmiechnięta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3237,1831,0,'sumienny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3237,1831,1,'punktualny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3237,1831,2,'bezkonfliktowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3239,1832,0,'empatyczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3239,1832,1,'szczera');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3239,1832,2,'ciekawska');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3243,1833,0,'otwarty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3243,1833,1,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3243,1833,2,'pracowity');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3245,1834,0,'uczciwy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3245,1834,1,'sumienny ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3245,1834,2,'ugodowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3247,1835,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3247,1835,1,'odpowiedzialna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3247,1835,2,'pełna empatii');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3249,1836,0,'Kreatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3249,1836,1,'Ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3249,1836,2,'Spontaniczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3251,1837,0,'sumienność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3251,1837,1,'solidność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3251,1837,2,'cierpliwość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3253,1838,0,'uśmiechnięta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3253,1838,1,'pracowita/ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3253,1838,2,'komunikatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3255,1839,0,'uśmiechnięta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3255,1839,1,'pracowita/ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3255,1839,2,'komunikatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3258,1840,0,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3258,1840,1,'uczynny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3258,1840,2,'zaangażowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3260,1841,0,'tworzenie biznesow przez współprace z udzmi z roznych branży  i jednoczesnie budowanie swojej niezaleznosci finansowej i wolnosci  ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3260,1841,1,' nieustanny rozwój  i poznawanie swoich mozliwosci z jednoczesnym przełamywaniem ograniczne ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3260,1841,2,'uczenie siebie zeby móc uczyć inych ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3262,1842,0,'pomysłowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3262,1842,1,'żywiołowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3262,1842,2,'otwarty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3264,1843,0,'uczciwy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3264,1843,1,'pewny siebie');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3264,1843,2,'lenistwo');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3266,1844,0,'Ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3266,1844,1,'Otwarta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3266,1844,2,'Obowiązkowa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3268,1845,0,'konkretny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3268,1845,1,'uśmiechnięty (w sumie to nie przymiotnik, ale niech będzie ;))');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3268,1845,2,'niepokorny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3270,1846,0,'dokładna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3270,1846,1,'kontaktowa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3270,1846,2,'Uprzejma');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3272,1847,0,'dokładna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3272,1847,1,'kontaktowa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3272,1847,2,'Uprzejma');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3274,1848,0,'przebojowa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3274,1848,1,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3274,1848,2,'uparta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3276,1849,0,'komunikatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3276,1849,1,'precyzyjna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3276,1849,2,'pracowita');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3278,1850,0,'cierpliwy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3278,1850,1,'kompromisowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3278,1850,2,'odporny na stres');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3280,1851,0,'zaangażowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3280,1851,1,'uporządkowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3280,1851,2,'altruistyczny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3282,1852,0,'towarzyska ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3282,1852,1,'odpowiedzialna ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3282,1852,2,'otwarta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3284,1853,0,'komunikatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3284,1853,1,'kompetentna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3284,1853,2,'rozsądna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3286,1854,0,'upór');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3286,1854,1,'ambicja');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3286,1854,2,'intuicja');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3288,1855,0,'Ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3288,1855,1,'Komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3288,1855,2,'Pozytywnie nastawiony');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3290,1856,0,'sumienność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3290,1856,1,'dokładność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3290,1856,2,'niezależność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3292,1857,0,'sumienność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3292,1857,1,'dokładność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3292,1857,2,'niezależność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3294,1858,0,'komunikatywność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3294,1858,1,'solidność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3294,1858,2,'optymistyczne,aczkolwiek rozsądne podejście do życia:D');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3296,1859,0,'konkretny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3296,1859,1,'charyzmatyczny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3296,1859,2,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3298,1860,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3298,1860,1,'punktualna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3298,1860,2,'odpowiedzialna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3300,1861,0,'otwarta');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3300,1861,1,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3300,1861,2,'wrażliwa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3302,1862,0,'dobrze zorganizowana');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3302,1862,1,'przywódcza');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3302,1862,2,'kreatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3304,1863,0,'odpowiedzialność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3304,1863,1,'optymizm');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3304,1863,2,'skrytość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3306,1864,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3306,1864,1,'przedsiębiorcza');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3306,1864,2,'charyzmatyczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3308,1865,0,'pogodna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3308,1865,1,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3308,1865,2,'towarzyska');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3310,1866,0,'leniwy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3310,1866,1,'niezorganizowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3310,1866,2,'spokojny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3312,1867,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3312,1867,1,'kreatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3312,1867,2,'zaangażowana');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3314,1868,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3314,1868,1,'kreatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3314,1868,2,'zaangażowana');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3316,1869,0,'otwartosc na zmiany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3316,1869,1,'wysoki poziom energi');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3316,1869,2,'wytrwałosc');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3318,1870,0,'energiczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3318,1870,1,'komunikatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3318,1870,2,'nieprzeciętna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3320,1871,0,'uczciwość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3320,1871,1,'pracowitość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3320,1871,2,'cierpliwość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3322,1872,0,'odpowiedzialna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3322,1872,1,'pogodna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3322,1872,2,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3324,1873,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3324,1873,1,'skrupulatna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3324,1873,2,'spontaniczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3326,1874,0,'łatwość nawiązywania kontaktów');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3326,1874,1,'zaangażowanie w wykonywaniu pracy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3326,1874,2,'wysoka kultura osobista');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3328,1875,0,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3328,1875,1,'punktualny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3328,1875,2,'ucziwy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3330,1876,0,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3330,1876,1,'punktualny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3330,1876,2,'ucziwy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3332,1877,0,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3332,1877,1,'przyjacielski');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3332,1877,2,'kreatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3334,1878,0,'spokojny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3334,1878,1,'przy nieznajomych dosyć nieśmiały');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3334,1878,2,'pomysłowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3336,1879,0,'komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3336,1879,1,'otwarty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3336,1879,2,'zawzięty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3338,1880,0,'komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3338,1880,1,'otwarty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3338,1880,2,'zawzięty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3340,1881,0,'zaradna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3340,1881,1,'kreatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3340,1881,2,'wesoła');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3342,1882,0,'Odpowiedzialna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3342,1882,1,'Uczciwa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3342,1882,2,'Solidna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3344,1883,0,'wrodzone kombinatorstwo:)');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3344,1883,1,'łatwość nawiązywania kontaktów z ludźmi');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3344,1883,2,'poczucie chumoru');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3346,1884,0,'Pewny siebie');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3346,1884,1,'Słowny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3346,1884,2,'Pracowity');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3348,1885,0,'Pewność siebie');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3348,1885,1,'Pracowitość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3348,1885,2,'Słowność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3350,1886,0,'Pewność siebie');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3350,1886,1,'Pracowitość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3350,1886,2,'Słowność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3352,1887,0,'sumienny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3352,1887,1,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3352,1887,2,'pracowity');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3354,1888,0,'sumienny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3354,1888,1,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3354,1888,2,'pracowity');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3356,1889,0,'wrażliwa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3356,1889,1,'obowiązkowa');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3356,1889,2,'pracowita');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3358,1890,0,'Elokwencja');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3358,1890,1,'Optymiz');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3358,1890,2,'Pracowitosć');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3360,1891,0,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3360,1891,1,'konsekwentny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3360,1891,2,'zorganizowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3362,1892,0,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3362,1892,1,'punktualny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3362,1892,2,'komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3364,1893,0,'ambitna ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3364,1893,1,'zdeterminowana');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3364,1893,2,'komunikatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3366,1894,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3366,1894,1,'ciekawa nowości');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3366,1894,2,'odpowiedzialna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3369,1896,0,'pomysłowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3369,1896,1,'energiczny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3369,1896,2,'asertywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3371,1897,0,'komunikatywność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3371,1897,1,'szczerość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3371,1897,2,'dokładność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3373,1898,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3373,1898,1,'odpowiedzialna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3373,1898,2,'perfekcjonistka');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3375,1899,0,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3375,1899,1,'odpowiedzialna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3375,1899,2,'kreatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3377,1900,0,'wytrwałość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3377,1900,1,'kreatywność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3377,1900,2,'spostrzegawczość');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3379,1901,0,'Komunikatywność, otwartość i umiejętności pracy w zespole');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3379,1901,1,'Chęć rozwoju, zaangażowanie w pracę ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3379,1901,2,'Twórcze podejście do zadań');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3381,1902,0,'Komunikatywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3381,1902,1,'Bezpośredni');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3381,1902,2,'Wytrwały');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3383,1903,0,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3383,1903,1,'otwarty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3383,1903,2,'optymista');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3385,1904,0,'przebojowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3385,1904,1,'uniwersalny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3385,1904,2,'zorganizowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3387,1905,0,'ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3387,1905,1,'sumienny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3387,1905,2,'odważny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3389,1906,0,'Otwarty');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3389,1906,1,'Pozytywny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3389,1906,2,'Pomysłowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3391,1907,0,'energiczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3391,1907,1,'ambitna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3391,1907,2,'kominikatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3393,1908,0,'odpowiedzialny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3393,1908,1,'profesjonalny w zdrowy sposób');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3393,1908,2,'przyjacielski');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3395,1909,0,'wszechstronny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3395,1909,1,'sumienny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3395,1909,2,'ekstrawertyczny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3397,1910,0,'Komunikatywność, przedsiębiorczość, kreatywność, punktualność');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3397,1910,1,NULL);
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3397,1910,2,NULL);
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3399,1911,0,'wytrwały');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3399,1911,1,'zdeterminowany');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3399,1911,2,'entuzjastyczny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3401,1912,0,'otwarty, liberalny, ambitny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3401,1912,1,'tolerancyjny, kreatywny, pomysłowy');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3401,1912,2,'rozrywkowy, towarzyski, ');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3403,1913,0,'Punktualny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3403,1913,1,'Dokładny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3403,1913,2,'Optymistyczny');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3405,1914,0,'komunikatywna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3405,1914,1,'spontaniczna');
INSERT INTO `drupal_content_field_candidate_prcvd_qualities` VALUES (3405,1914,2,'aktywna');
/*!40000 ALTER TABLE `drupal_content_field_candidate_prcvd_qualities` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

