
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Not dumping tablespaces as no INFORMATION_SCHEMA.FILES table on this server
--
DROP TABLE IF EXISTS `drupal_content_node_field`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `drupal_content_node_field` (
  `field_name` varchar(32) NOT NULL default '',
  `type` varchar(127) NOT NULL default '',
  `global_settings` mediumtext NOT NULL,
  `required` tinyint(4) NOT NULL default '0',
  `multiple` tinyint(4) NOT NULL default '0',
  `db_storage` tinyint(4) NOT NULL default '1',
  `module` varchar(127) NOT NULL default '',
  `db_columns` mediumtext NOT NULL,
  `active` tinyint(4) NOT NULL default '0',
  `locked` tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (`field_name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `drupal_content_node_field` WRITE;
/*!40000 ALTER TABLE `drupal_content_node_field` DISABLE KEYS */;
INSERT INTO `drupal_content_node_field` VALUES ('field_link','link','a:6:{s:10:\"attributes\";a:3:{s:6:\"target\";s:7:\"default\";s:3:\"rel\";s:0:\"\";s:5:\"class\";s:0:\"\";}s:7:\"display\";a:1:{s:10:\"url_cutoff\";s:2:\"50\";}s:3:\"url\";i:0;s:5:\"title\";s:8:\"optional\";s:11:\"title_value\";s:0:\"\";s:13:\"enable_tokens\";i:0;}',0,1,0,'link','a:3:{s:3:\"url\";a:4:{s:4:\"type\";s:7:\"varchar\";s:6:\"length\";i:2048;s:8:\"not null\";b:0;s:8:\"sortable\";b:1;}s:5:\"title\";a:4:{s:4:\"type\";s:7:\"varchar\";s:6:\"length\";i:255;s:8:\"not null\";b:0;s:8:\"sortable\";b:1;}s:10:\"attributes\";a:3:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:6:\"medium\";s:8:\"not null\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_login','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',1,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_password','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',1,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_company_email_address','email','a:0:{}',0,0,1,'email','a:1:{s:5:\"email\";a:4:{s:4:\"type\";s:7:\"varchar\";s:6:\"length\";i:255;s:8:\"not null\";b:0;s:8:\"sortable\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_company_phone_number','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_position_user','userreference','a:4:{s:19:\"referenceable_roles\";a:18:{i:2;i:0;i:3;i:0;i:7;i:0;i:5;i:0;i:6;i:0;i:16;i:0;i:20;i:0;i:8;i:0;i:10;i:0;i:12;i:0;i:17;i:0;i:11;i:0;i:13;i:0;i:18;i:0;i:9;i:0;i:19;i:0;i:15;i:0;i:14;i:0;}s:20:\"referenceable_status\";s:1:\"1\";s:13:\"advanced_view\";s:2:\"--\";s:18:\"advanced_view_args\";s:0:\"\";}',0,0,1,'userreference','a:1:{s:3:\"uid\";a:4:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;s:5:\"index\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_discharge_status','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:2:\"17\";s:6:\"parent\";s:3:\"191\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_contact_history','text','a:4:{s:15:\"text_processing\";s:1:\"1\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:2:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}s:6:\"format\";a:4:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;s:5:\"views\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_team_position_function','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:1:\"4\";s:6:\"parent\";s:3:\"182\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_company_www_address','link','a:6:{s:10:\"attributes\";a:3:{s:6:\"target\";s:7:\"default\";s:3:\"rel\";s:0:\"\";s:5:\"class\";s:0:\"\";}s:7:\"display\";a:1:{s:10:\"url_cutoff\";s:2:\"80\";}s:3:\"url\";i:0;s:5:\"title\";s:4:\"none\";s:11:\"title_value\";s:0:\"\";s:13:\"enable_tokens\";i:0;}',0,0,1,'link','a:3:{s:3:\"url\";a:4:{s:4:\"type\";s:7:\"varchar\";s:6:\"length\";i:2048;s:8:\"not null\";b:0;s:8:\"sortable\";b:1;}s:5:\"title\";a:4:{s:4:\"type\";s:7:\"varchar\";s:6:\"length\";i:255;s:8:\"not null\";b:0;s:8:\"sortable\";b:1;}s:10:\"attributes\";a:3:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:6:\"medium\";s:8:\"not null\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_position_profile_uni','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:1:\"9\";s:6:\"parent\";s:3:\"135\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_company_name','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',1,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_department_name','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_contact_name','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_company_reference','nodereference','a:3:{s:19:\"referenceable_types\";a:9:{s:7:\"company\";s:7:\"company\";s:18:\"profile_ambassador\";i:0;s:7:\"contact\";i:0;s:19:\"profile_coordinator\";i:0;s:5:\"forum\";i:0;s:4:\"page\";i:0;s:4:\"poll\";i:0;s:7:\"service\";i:0;s:5:\"story\";i:0;}s:13:\"advanced_view\";s:2:\"--\";s:18:\"advanced_view_args\";s:0:\"\";}',1,0,1,'nodereference','a:1:{s:3:\"nid\";a:4:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;s:5:\"index\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_contact_phone_number','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_contact_email_address','email','a:0:{}',0,0,1,'email','a:1:{s:5:\"email\";a:4:{s:4:\"type\";s:7:\"varchar\";s:6:\"length\";i:255;s:8:\"not null\";b:0;s:8:\"sortable\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_company_branch','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:1:\"7\";s:6:\"parent\";s:1:\"0\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,1,0,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_company_contacts','viewfield','a:4:{s:13:\"allowed_views\";a:16:{s:16:\"company_contacts\";s:16:\"company_contacts\";s:8:\"services\";i:0;s:12:\"active_users\";i:0;s:17:\"coordinator_users\";i:0;s:16:\"ambassador_users\";i:0;s:15:\"comments_recent\";i:0;s:7:\"tracker\";i:0;s:9:\"frontpage\";i:0;s:8:\"glossary\";i:0;s:7:\"archive\";i:0;s:9:\"backlinks\";i:0;s:7:\"popular\";i:0;s:13:\"taxonomy_term\";i:0;s:14:\"location_table\";i:0;s:18:\"location_directory\";i:0;s:19:\"user_location_table\";i:0;}s:13:\"super_default\";i:1;s:13:\"token_enabled\";i:0;s:20:\"super_default_widget\";a:1:{i:0;a:2:{s:5:\"vargs\";s:4:\"%nid\";s:5:\"vname\";s:24:\"company_contacts|default\";}}}',1,0,1,'viewfield','a:2:{s:5:\"vname\";a:3:{s:4:\"type\";s:7:\"varchar\";s:8:\"not null\";b:0;s:6:\"length\";i:32;}s:5:\"vargs\";a:3:{s:4:\"type\";s:7:\"varchar\";s:8:\"not null\";b:0;s:6:\"length\";i:255;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_general_assembly_number','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',1,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_company_fax_number','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_company_postal_address','location','a:1:{s:17:\"location_settings\";a:2:{s:4:\"form\";a:1:{s:6:\"fields\";a:8:{s:4:\"name\";a:3:{s:7:\"collect\";s:1:\"0\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"2\";}s:6:\"street\";a:3:{s:7:\"collect\";s:1:\"1\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"4\";}s:10:\"additional\";a:3:{s:7:\"collect\";s:1:\"0\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"6\";}s:4:\"city\";a:3:{s:7:\"collect\";s:1:\"1\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"8\";}s:8:\"province\";a:3:{s:7:\"collect\";s:1:\"0\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:2:\"10\";}s:11:\"postal_code\";a:3:{s:7:\"collect\";s:1:\"1\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:2:\"12\";}s:7:\"country\";a:3:{s:7:\"collect\";s:1:\"1\";s:7:\"default\";s:2:\"pl\";s:6:\"weight\";s:2:\"14\";}s:7:\"locpick\";a:2:{s:7:\"collect\";s:1:\"0\";s:6:\"weight\";s:2:\"20\";}}}s:7:\"display\";a:1:{s:4:\"hide\";a:12:{s:4:\"name\";i:0;s:6:\"street\";i:0;s:10:\"additional\";i:0;s:4:\"city\";i:0;s:8:\"province\";i:0;s:11:\"postal_code\";i:0;s:7:\"country\";i:0;s:7:\"locpick\";i:0;s:13:\"province_name\";i:0;s:12:\"country_name\";i:0;s:8:\"map_link\";i:0;s:6:\"coords\";i:0;}}}}',0,0,1,'location_cck','a:1:{s:3:\"lid\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_contact_position','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_first_name','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',1,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_last_name','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',1,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_birth_date','date','a:7:{s:11:\"granularity\";a:3:{s:4:\"year\";s:4:\"year\";s:5:\"month\";s:5:\"month\";s:3:\"day\";s:3:\"day\";}s:11:\"timezone_db\";s:0:\"\";s:11:\"tz_handling\";s:4:\"none\";s:6:\"todate\";s:0:\"\";s:6:\"repeat\";i:0;s:16:\"repeat_collapsed\";s:0:\"\";s:14:\"default_format\";s:6:\"medium\";}',1,0,1,'date','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:7:\"varchar\";s:6:\"length\";i:20;s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_phone_number','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',1,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_email_address','email','a:0:{}',1,0,1,'email','a:1:{s:5:\"email\";a:4:{s:4:\"type\";s:7:\"varchar\";s:6:\"length\";i:255;s:8:\"not null\";b:0;s:8:\"sortable\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_home_address','location','a:1:{s:17:\"location_settings\";a:2:{s:4:\"form\";a:1:{s:6:\"fields\";a:8:{s:4:\"name\";a:3:{s:7:\"collect\";s:1:\"0\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"2\";}s:6:\"street\";a:3:{s:7:\"collect\";s:1:\"2\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"4\";}s:10:\"additional\";a:3:{s:7:\"collect\";s:1:\"0\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"6\";}s:4:\"city\";a:3:{s:7:\"collect\";s:1:\"2\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"8\";}s:8:\"province\";a:3:{s:7:\"collect\";s:1:\"0\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:2:\"10\";}s:11:\"postal_code\";a:3:{s:7:\"collect\";s:1:\"2\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:2:\"12\";}s:7:\"country\";a:3:{s:7:\"collect\";s:1:\"4\";s:7:\"default\";s:2:\"pl\";s:6:\"weight\";s:2:\"14\";}s:7:\"locpick\";a:2:{s:7:\"collect\";s:1:\"0\";s:6:\"weight\";s:2:\"20\";}}}s:7:\"display\";a:1:{s:4:\"hide\";a:12:{s:4:\"name\";i:0;s:6:\"street\";i:0;s:10:\"additional\";i:0;s:4:\"city\";i:0;s:8:\"province\";i:0;s:11:\"postal_code\";i:0;s:7:\"country\";i:0;s:7:\"locpick\";i:0;s:13:\"province_name\";i:0;s:12:\"country_name\";i:0;s:8:\"map_link\";i:0;s:6:\"coords\";i:0;}}}}',1,0,1,'location_cck','a:1:{s:3:\"lid\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_address','location','a:1:{s:17:\"location_settings\";a:2:{s:4:\"form\";a:1:{s:6:\"fields\";a:8:{s:4:\"name\";a:3:{s:7:\"collect\";s:1:\"0\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"2\";}s:6:\"street\";a:3:{s:7:\"collect\";s:1:\"2\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"4\";}s:10:\"additional\";a:3:{s:7:\"collect\";s:1:\"0\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"6\";}s:4:\"city\";a:3:{s:7:\"collect\";s:1:\"2\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:1:\"8\";}s:8:\"province\";a:3:{s:7:\"collect\";s:1:\"0\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:2:\"10\";}s:11:\"postal_code\";a:3:{s:7:\"collect\";s:1:\"2\";s:7:\"default\";s:0:\"\";s:6:\"weight\";s:2:\"12\";}s:7:\"country\";a:3:{s:7:\"collect\";s:1:\"4\";s:7:\"default\";s:2:\"pl\";s:6:\"weight\";s:2:\"14\";}s:7:\"locpick\";a:2:{s:7:\"collect\";s:1:\"0\";s:6:\"weight\";s:2:\"20\";}}}s:7:\"display\";a:1:{s:4:\"hide\";a:12:{s:4:\"name\";i:0;s:6:\"street\";i:0;s:10:\"additional\";i:0;s:4:\"city\";i:0;s:8:\"province\";i:0;s:11:\"postal_code\";i:0;s:7:\"country\";i:0;s:7:\"locpick\";i:0;s:13:\"province_name\";i:0;s:12:\"country_name\";i:0;s:8:\"map_link\";i:0;s:6:\"coords\";i:0;}}}}',0,0,1,'location_cck','a:1:{s:3:\"lid\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_at_home','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:9:\"no\r\nyes\r\n\";s:18:\"allowed_values_php\";s:0:\"\";}',1,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_ref_chnnl_other','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_int_references','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_uni_other','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_major','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_minor','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_degree','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:2:\"10\";s:6:\"parent\";s:3:\"158\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_uni','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:1:\"9\";s:6:\"parent\";s:3:\"134\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_language_name','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_language_skill','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_prcvd_qualities','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',1,3,0,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_org_activity','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_results','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:2:\"14\";s:6:\"parent\";s:3:\"169\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_year','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:2:\"15\";s:6:\"parent\";s:3:\"171\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_competition_part','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_other_achieves','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_work_experience','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_residence_abroad','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_language_certs','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_own_interests','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_apply_reasons','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_planned_activity','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_data_agreement','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:217:\"Wyrażam zgodę na przechowywanie i przetwarzanie moich danych osobowych zawartych w powyższej aplikacji przez Cognitis (zgodnie z Ustawą z 2002 roku o Ochronie Danych Osobowych, Dz. U. Nr 101 poz, 926 ze zmianami).\";s:18:\"allowed_values_php\";s:0:\"\";}',1,1,0,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_extra','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_main','flexifield','a:1:{s:10:\"item_types\";a:15:{s:27:\"application_candidate_study\";s:27:\"application_candidate_study\";s:18:\"profile_ambassador\";i:0;s:21:\"application_candidate\";i:0;s:30:\"application_candidate_language\";i:0;s:7:\"company\";i:0;s:7:\"contact\";i:0;s:19:\"profile_coordinator\";i:0;s:5:\"forum\";i:0;s:18:\"internal_wiki_page\";i:0;s:10:\"simplenews\";i:0;s:4:\"page\";i:0;s:4:\"poll\";i:0;s:11:\"public_page\";i:0;s:12:\"public_story\";i:0;s:7:\"service\";i:0;}}',0,0,1,'flexifield','a:3:{s:4:\"type\";a:5:{s:4:\"type\";s:7:\"varchar\";s:6:\"length\";i:32;s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:0;}s:5:\"value\";a:6:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;s:9:\"serialize\";b:1;s:5:\"views\";b:0;}s:7:\"item_id\";a:4:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_lang_skill_en','content_taxonomy','a:5:{s:14:\"save_term_node\";i:0;s:3:\"vid\";s:2:\"11\";s:6:\"parent\";s:1:\"0\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_lang_skill_de','content_taxonomy','a:5:{s:14:\"save_term_node\";i:0;s:3:\"vid\";s:2:\"11\";s:6:\"parent\";s:1:\"0\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_lang_skill_fr','content_taxonomy','a:5:{s:14:\"save_term_node\";i:0;s:3:\"vid\";s:2:\"11\";s:6:\"parent\";s:1:\"0\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_lang_skill_es','content_taxonomy','a:5:{s:14:\"save_term_node\";i:0;s:3:\"vid\";s:2:\"11\";s:6:\"parent\";s:1:\"0\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_lang_skill_ru','content_taxonomy','a:5:{s:14:\"save_term_node\";i:0;s:3:\"vid\";s:2:\"11\";s:6:\"parent\";s:1:\"0\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_lang_other_name','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_lang_other_skill','content_taxonomy','a:5:{s:14:\"save_term_node\";i:0;s:3:\"vid\";s:2:\"11\";s:6:\"parent\";s:1:\"0\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_ref_channel','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:2:\"12\";s:6:\"parent\";s:3:\"155\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_apply_city_auto','computed','a:8:{s:4:\"code\";s:470:\"$study = $node->field_candidate_study_main[0][\'value\'];\r\n\r\nif (is_string($study)) {\r\n  $study =  unserialize($study);\r\n}\r\n\r\n$uni = taxonomy_get_term($study[\'field_candidate_study_uni\'][0][\'value\']);\r\n$node_field[0][\'value\'] = $uni->name;\r\n$parents1 = taxonomy_get_parents($uni->tid);\r\nif (count($parents1) > 0) {\r\n  $parents2 = taxonomy_get_parents(current($parents1)->tid);\r\n  if (count($parents2) > 0) {\r\n    $node_field[0][\'value\'] = current($parents1)->name;\r\n  }\r\n}\";s:14:\"display_format\";s:37:\"$display = $node_field_item[\'value\'];\";s:5:\"store\";i:0;s:9:\"data_type\";s:7:\"varchar\";s:11:\"data_length\";s:3:\"255\";s:13:\"data_not_NULL\";i:0;s:12:\"data_default\";s:0:\"\";s:13:\"data_sortable\";i:1;}',0,0,1,'computed_field','a:0:{}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_team_team','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:2:\"16\";s:6:\"parent\";s:1:\"0\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,0,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_team_term','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:1:\"5\";s:6:\"parent\";s:1:\"0\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,0,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_candidate_study_mode','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:2:\"13\";s:6:\"parent\";s:3:\"157\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_position_profile_hobby','text','a:4:{s:15:\"text_processing\";s:1:\"0\";s:10:\"max_length\";s:0:\"\";s:14:\"allowed_values\";s:0:\"\";s:18:\"allowed_values_php\";s:0:\"\";}',0,0,1,'text','a:1:{s:5:\"value\";a:5:{s:4:\"type\";s:4:\"text\";s:4:\"size\";s:3:\"big\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_position_profile_position','nodereference','a:3:{s:19:\"referenceable_types\";a:16:{s:13:\"team_position\";s:13:\"team_position\";s:21:\"application_candidate\";i:0;s:30:\"application_candidate_language\";i:0;s:27:\"application_candidate_study\";i:0;s:7:\"company\";i:0;s:7:\"contact\";i:0;s:5:\"forum\";i:0;s:13:\"internal_page\";i:0;s:18:\"internal_wiki_page\";i:0;s:10:\"simplenews\";i:0;s:4:\"poll\";i:0;s:16:\"position_profile\";i:0;s:11:\"public_page\";i:0;s:12:\"public_story\";i:0;s:7:\"service\";i:0;s:4:\"team\";i:0;}s:13:\"advanced_view\";s:2:\"--\";s:18:\"advanced_view_args\";s:0:\"\";}',1,0,1,'nodereference','a:1:{s:3:\"nid\";a:4:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;s:5:\"index\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_election_status','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:2:\"17\";s:6:\"parent\";s:3:\"187\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_event_datetime','datetime','a:7:{s:11:\"granularity\";a:5:{s:4:\"year\";s:4:\"year\";s:5:\"month\";s:5:\"month\";s:3:\"day\";s:3:\"day\";s:4:\"hour\";s:4:\"hour\";s:6:\"minute\";s:6:\"minute\";}s:11:\"timezone_db\";s:3:\"UTC\";s:11:\"tz_handling\";s:4:\"site\";s:6:\"todate\";s:8:\"optional\";s:6:\"repeat\";i:0;s:16:\"repeat_collapsed\";s:0:\"\";s:14:\"default_format\";s:5:\"short\";}',1,0,1,'date','a:2:{s:5:\"value\";a:4:{s:4:\"type\";s:8:\"datetime\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:1;}s:6:\"value2\";a:4:{s:4:\"type\";s:8:\"datetime\";s:8:\"not null\";b:0;s:8:\"sortable\";b:1;s:5:\"views\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_general_assembly_protocol','filefield','a:3:{s:10:\"list_field\";s:1:\"0\";s:12:\"list_default\";i:1;s:17:\"description_field\";s:1:\"0\";}',0,0,1,'filefield','a:3:{s:3:\"fid\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:5:\"views\";b:1;}s:4:\"list\";a:4:{s:4:\"type\";s:3:\"int\";s:4:\"size\";s:4:\"tiny\";s:8:\"not null\";b:0;s:5:\"views\";b:1;}s:4:\"data\";a:3:{s:4:\"type\";s:4:\"text\";s:9:\"serialize\";b:1;s:5:\"views\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_gnrl_assmbl_tm_elctns','viewfield','a:4:{s:13:\"allowed_views\";a:26:{s:26:\"general_assembly_tm_elctns\";s:26:\"general_assembly_tm_elctns\";s:8:\"services\";i:0;s:12:\"active_users\";i:0;s:13:\"users_in_role\";i:0;s:16:\"company_contacts\";i:0;s:9:\"companies\";i:0;s:17:\"frontpage_stories\";i:0;s:22:\"candidate_applications\";i:0;s:13:\"users_by_role\";i:0;s:11:\"empty_nodes\";i:0;s:18:\"general_assemblies\";i:0;s:27:\"general_assembly_tm_dschrgs\";i:0;s:15:\"comments_recent\";i:0;s:7:\"tracker\";i:0;s:9:\"frontpage\";i:0;s:8:\"glossary\";i:0;s:7:\"archive\";i:0;s:9:\"backlinks\";i:0;s:7:\"popular\";i:0;s:13:\"taxonomy_term\";i:0;s:12:\"date_browser\";i:0;s:14:\"location_table\";i:0;s:18:\"location_directory\";i:0;s:19:\"user_location_table\";i:0;s:15:\"rules_scheduler\";i:0;s:13:\"admin_content\";i:0;}s:13:\"super_default\";i:1;s:13:\"token_enabled\";i:0;s:20:\"super_default_widget\";a:2:{s:5:\"vname\";s:34:\"general_assembly_tm_elctns|default\";s:5:\"vargs\";s:4:\"%nid\";}}',1,0,1,'viewfield','a:2:{s:5:\"vname\";a:3:{s:4:\"type\";s:7:\"varchar\";s:8:\"not null\";b:0;s:6:\"length\";i:32;}s:5:\"vargs\";a:3:{s:4:\"type\";s:7:\"varchar\";s:8:\"not null\";b:0;s:6:\"length\";i:255;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_election_general_assembly','nodereference','a:3:{s:19:\"referenceable_types\";a:19:{s:16:\"general_assembly\";s:16:\"general_assembly\";s:21:\"application_candidate\";i:0;s:30:\"application_candidate_language\";i:0;s:27:\"application_candidate_study\";i:0;s:7:\"company\";i:0;s:7:\"contact\";i:0;s:5:\"forum\";i:0;s:13:\"internal_page\";i:0;s:18:\"internal_wiki_page\";i:0;s:18:\"member_application\";i:0;s:10:\"simplenews\";i:0;s:4:\"poll\";i:0;s:16:\"position_profile\";i:0;s:11:\"public_page\";i:0;s:12:\"public_story\";i:0;s:7:\"service\";i:0;s:4:\"team\";i:0;s:13:\"team_position\";i:0;s:7:\"webform\";i:0;}s:13:\"advanced_view\";s:25:\"general_assemblies_lookup\";s:18:\"advanced_view_args\";s:0:\"\";}',1,0,1,'nodereference','a:1:{s:3:\"nid\";a:4:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;s:5:\"index\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_discharge_general_assembly','nodereference','a:3:{s:19:\"referenceable_types\";a:19:{s:16:\"general_assembly\";s:16:\"general_assembly\";s:21:\"application_candidate\";i:0;s:30:\"application_candidate_language\";i:0;s:27:\"application_candidate_study\";i:0;s:7:\"company\";i:0;s:7:\"contact\";i:0;s:5:\"forum\";i:0;s:13:\"internal_page\";i:0;s:18:\"internal_wiki_page\";i:0;s:18:\"member_application\";i:0;s:10:\"simplenews\";i:0;s:4:\"poll\";i:0;s:16:\"position_profile\";i:0;s:11:\"public_page\";i:0;s:12:\"public_story\";i:0;s:7:\"service\";i:0;s:4:\"team\";i:0;s:13:\"team_position\";i:0;s:7:\"webform\";i:0;}s:13:\"advanced_view\";s:25:\"general_assemblies_lookup\";s:18:\"advanced_view_args\";s:0:\"\";}',0,0,1,'nodereference','a:1:{s:3:\"nid\";a:4:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;s:5:\"index\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_nmntn_general_assembly','nodereference','a:3:{s:19:\"referenceable_types\";a:19:{s:16:\"general_assembly\";s:16:\"general_assembly\";s:21:\"application_candidate\";i:0;s:30:\"application_candidate_language\";i:0;s:27:\"application_candidate_study\";i:0;s:7:\"company\";i:0;s:7:\"contact\";i:0;s:5:\"forum\";i:0;s:13:\"internal_page\";i:0;s:18:\"internal_wiki_page\";i:0;s:18:\"member_application\";i:0;s:10:\"simplenews\";i:0;s:4:\"poll\";i:0;s:16:\"position_profile\";i:0;s:11:\"public_page\";i:0;s:12:\"public_story\";i:0;s:7:\"service\";i:0;s:4:\"team\";i:0;s:13:\"team_position\";i:0;s:7:\"webform\";i:0;}s:13:\"advanced_view\";s:2:\"--\";s:18:\"advanced_view_args\";s:0:\"\";}',1,0,1,'nodereference','a:1:{s:3:\"nid\";a:4:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;s:5:\"index\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_user','userreference','a:4:{s:19:\"referenceable_roles\";a:18:{i:2;i:0;i:3;i:0;i:7;i:0;i:5;i:0;i:6;i:0;i:16;i:0;i:20;i:0;i:8;i:0;i:10;i:0;i:12;i:0;i:17;i:0;i:11;i:0;i:13;i:0;i:18;i:0;i:9;i:0;i:19;i:0;i:15;i:0;i:14;i:0;}s:20:\"referenceable_status\";s:1:\"1\";s:13:\"advanced_view\";s:2:\"--\";s:18:\"advanced_view_args\";s:0:\"\";}',1,0,1,'userreference','a:1:{s:3:\"uid\";a:4:{s:4:\"type\";s:3:\"int\";s:8:\"unsigned\";b:1;s:8:\"not null\";b:0;s:5:\"index\";b:1;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_member_status','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:2:\"18\";s:6:\"parent\";s:3:\"198\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_gnrl_assmbl_stts_elctns','viewfield','a:4:{s:13:\"allowed_views\";s:0:\"\";s:13:\"super_default\";s:0:\"\";s:13:\"token_enabled\";s:0:\"\";s:20:\"super_default_widget\";s:0:\"\";}',0,0,1,'viewfield','a:2:{s:5:\"vname\";a:3:{s:4:\"type\";s:7:\"varchar\";s:8:\"not null\";b:0;s:6:\"length\";i:32;}s:5:\"vargs\";a:3:{s:4:\"type\";s:7:\"varchar\";s:8:\"not null\";b:0;s:6:\"length\";i:255;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_gnrl_assmbl_tm_dschrgs','viewfield','a:4:{s:13:\"allowed_views\";a:25:{s:27:\"general_assembly_tm_dschrgs\";s:27:\"general_assembly_tm_dschrgs\";s:8:\"services\";i:0;s:12:\"active_users\";i:0;s:13:\"users_in_role\";i:0;s:16:\"company_contacts\";i:0;s:9:\"companies\";i:0;s:17:\"frontpage_stories\";i:0;s:22:\"candidate_applications\";i:0;s:13:\"users_by_role\";i:0;s:11:\"empty_nodes\";i:0;s:18:\"general_assemblies\";i:0;s:15:\"comments_recent\";i:0;s:7:\"tracker\";i:0;s:9:\"frontpage\";i:0;s:8:\"glossary\";i:0;s:7:\"archive\";i:0;s:9:\"backlinks\";i:0;s:7:\"popular\";i:0;s:13:\"taxonomy_term\";i:0;s:12:\"date_browser\";i:0;s:14:\"location_table\";i:0;s:18:\"location_directory\";i:0;s:19:\"user_location_table\";i:0;s:15:\"rules_scheduler\";i:0;s:13:\"admin_content\";i:0;}s:13:\"super_default\";i:0;s:13:\"token_enabled\";i:0;s:20:\"super_default_widget\";a:2:{s:5:\"vname\";s:35:\"general_assembly_tm_dschrgs|default\";s:5:\"vargs\";s:4:\"%nid\";}}',1,0,1,'viewfield','a:2:{s:5:\"vname\";a:3:{s:4:\"type\";s:7:\"varchar\";s:8:\"not null\";b:0;s:6:\"length\";i:32;}s:5:\"vargs\";a:3:{s:4:\"type\";s:7:\"varchar\";s:8:\"not null\";b:0;s:6:\"length\";i:255;}}',1,0);
INSERT INTO `drupal_content_node_field` VALUES ('field_nomination_status','content_taxonomy','a:5:{s:14:\"save_term_node\";i:1;s:3:\"vid\";s:2:\"17\";s:6:\"parent\";s:3:\"201\";s:15:\"parent_php_code\";s:0:\"\";s:5:\"depth\";s:0:\"\";}',1,0,1,'content_taxonomy','a:1:{s:5:\"value\";a:3:{s:4:\"type\";s:3:\"int\";s:8:\"not null\";b:0;s:8:\"sortable\";b:0;}}',1,0);
/*!40000 ALTER TABLE `drupal_content_node_field` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

