
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Not dumping tablespaces as no INFORMATION_SCHEMA.FILES table on this server
--
DROP TABLE IF EXISTS `drupal_flexifield_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `drupal_flexifield_items` (
  `item_id` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`item_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `drupal_flexifield_items` WRITE;
/*!40000 ALTER TABLE `drupal_flexifield_items` DISABLE KEYS */;
INSERT INTO `drupal_flexifield_items` VALUES (3155);
INSERT INTO `drupal_flexifield_items` VALUES (3156);
INSERT INTO `drupal_flexifield_items` VALUES (3157);
INSERT INTO `drupal_flexifield_items` VALUES (3166);
INSERT INTO `drupal_flexifield_items` VALUES (3167);
INSERT INTO `drupal_flexifield_items` VALUES (3168);
INSERT INTO `drupal_flexifield_items` VALUES (3169);
INSERT INTO `drupal_flexifield_items` VALUES (3170);
INSERT INTO `drupal_flexifield_items` VALUES (3171);
INSERT INTO `drupal_flexifield_items` VALUES (3172);
INSERT INTO `drupal_flexifield_items` VALUES (3173);
INSERT INTO `drupal_flexifield_items` VALUES (3174);
INSERT INTO `drupal_flexifield_items` VALUES (3175);
INSERT INTO `drupal_flexifield_items` VALUES (3176);
INSERT INTO `drupal_flexifield_items` VALUES (3177);
INSERT INTO `drupal_flexifield_items` VALUES (3178);
INSERT INTO `drupal_flexifield_items` VALUES (3179);
INSERT INTO `drupal_flexifield_items` VALUES (3180);
INSERT INTO `drupal_flexifield_items` VALUES (3181);
INSERT INTO `drupal_flexifield_items` VALUES (3182);
INSERT INTO `drupal_flexifield_items` VALUES (3183);
INSERT INTO `drupal_flexifield_items` VALUES (3184);
INSERT INTO `drupal_flexifield_items` VALUES (3185);
INSERT INTO `drupal_flexifield_items` VALUES (3186);
INSERT INTO `drupal_flexifield_items` VALUES (3187);
INSERT INTO `drupal_flexifield_items` VALUES (3188);
INSERT INTO `drupal_flexifield_items` VALUES (3189);
INSERT INTO `drupal_flexifield_items` VALUES (3190);
INSERT INTO `drupal_flexifield_items` VALUES (3191);
INSERT INTO `drupal_flexifield_items` VALUES (3192);
INSERT INTO `drupal_flexifield_items` VALUES (3193);
INSERT INTO `drupal_flexifield_items` VALUES (3194);
INSERT INTO `drupal_flexifield_items` VALUES (3195);
INSERT INTO `drupal_flexifield_items` VALUES (3196);
INSERT INTO `drupal_flexifield_items` VALUES (3197);
INSERT INTO `drupal_flexifield_items` VALUES (3198);
INSERT INTO `drupal_flexifield_items` VALUES (3199);
INSERT INTO `drupal_flexifield_items` VALUES (3200);
INSERT INTO `drupal_flexifield_items` VALUES (3201);
INSERT INTO `drupal_flexifield_items` VALUES (3202);
INSERT INTO `drupal_flexifield_items` VALUES (3204);
INSERT INTO `drupal_flexifield_items` VALUES (3208);
INSERT INTO `drupal_flexifield_items` VALUES (3210);
INSERT INTO `drupal_flexifield_items` VALUES (3213);
INSERT INTO `drupal_flexifield_items` VALUES (3215);
INSERT INTO `drupal_flexifield_items` VALUES (3217);
INSERT INTO `drupal_flexifield_items` VALUES (3219);
INSERT INTO `drupal_flexifield_items` VALUES (3221);
INSERT INTO `drupal_flexifield_items` VALUES (3224);
INSERT INTO `drupal_flexifield_items` VALUES (3226);
INSERT INTO `drupal_flexifield_items` VALUES (3228);
INSERT INTO `drupal_flexifield_items` VALUES (3230);
INSERT INTO `drupal_flexifield_items` VALUES (3232);
INSERT INTO `drupal_flexifield_items` VALUES (3234);
INSERT INTO `drupal_flexifield_items` VALUES (3236);
INSERT INTO `drupal_flexifield_items` VALUES (3238);
INSERT INTO `drupal_flexifield_items` VALUES (3240);
INSERT INTO `drupal_flexifield_items` VALUES (3244);
INSERT INTO `drupal_flexifield_items` VALUES (3246);
INSERT INTO `drupal_flexifield_items` VALUES (3248);
INSERT INTO `drupal_flexifield_items` VALUES (3250);
INSERT INTO `drupal_flexifield_items` VALUES (3252);
INSERT INTO `drupal_flexifield_items` VALUES (3254);
INSERT INTO `drupal_flexifield_items` VALUES (3256);
INSERT INTO `drupal_flexifield_items` VALUES (3259);
INSERT INTO `drupal_flexifield_items` VALUES (3261);
INSERT INTO `drupal_flexifield_items` VALUES (3263);
INSERT INTO `drupal_flexifield_items` VALUES (3265);
INSERT INTO `drupal_flexifield_items` VALUES (3267);
INSERT INTO `drupal_flexifield_items` VALUES (3269);
INSERT INTO `drupal_flexifield_items` VALUES (3271);
INSERT INTO `drupal_flexifield_items` VALUES (3273);
INSERT INTO `drupal_flexifield_items` VALUES (3275);
INSERT INTO `drupal_flexifield_items` VALUES (3277);
INSERT INTO `drupal_flexifield_items` VALUES (3279);
INSERT INTO `drupal_flexifield_items` VALUES (3281);
INSERT INTO `drupal_flexifield_items` VALUES (3283);
INSERT INTO `drupal_flexifield_items` VALUES (3285);
INSERT INTO `drupal_flexifield_items` VALUES (3287);
INSERT INTO `drupal_flexifield_items` VALUES (3289);
INSERT INTO `drupal_flexifield_items` VALUES (3291);
INSERT INTO `drupal_flexifield_items` VALUES (3293);
INSERT INTO `drupal_flexifield_items` VALUES (3295);
INSERT INTO `drupal_flexifield_items` VALUES (3297);
INSERT INTO `drupal_flexifield_items` VALUES (3299);
INSERT INTO `drupal_flexifield_items` VALUES (3301);
INSERT INTO `drupal_flexifield_items` VALUES (3303);
INSERT INTO `drupal_flexifield_items` VALUES (3305);
INSERT INTO `drupal_flexifield_items` VALUES (3307);
INSERT INTO `drupal_flexifield_items` VALUES (3309);
INSERT INTO `drupal_flexifield_items` VALUES (3311);
INSERT INTO `drupal_flexifield_items` VALUES (3313);
INSERT INTO `drupal_flexifield_items` VALUES (3315);
INSERT INTO `drupal_flexifield_items` VALUES (3317);
INSERT INTO `drupal_flexifield_items` VALUES (3319);
INSERT INTO `drupal_flexifield_items` VALUES (3321);
INSERT INTO `drupal_flexifield_items` VALUES (3323);
INSERT INTO `drupal_flexifield_items` VALUES (3325);
INSERT INTO `drupal_flexifield_items` VALUES (3327);
INSERT INTO `drupal_flexifield_items` VALUES (3329);
INSERT INTO `drupal_flexifield_items` VALUES (3331);
INSERT INTO `drupal_flexifield_items` VALUES (3333);
INSERT INTO `drupal_flexifield_items` VALUES (3335);
INSERT INTO `drupal_flexifield_items` VALUES (3337);
INSERT INTO `drupal_flexifield_items` VALUES (3339);
INSERT INTO `drupal_flexifield_items` VALUES (3341);
INSERT INTO `drupal_flexifield_items` VALUES (3343);
INSERT INTO `drupal_flexifield_items` VALUES (3345);
INSERT INTO `drupal_flexifield_items` VALUES (3347);
INSERT INTO `drupal_flexifield_items` VALUES (3349);
INSERT INTO `drupal_flexifield_items` VALUES (3351);
INSERT INTO `drupal_flexifield_items` VALUES (3353);
INSERT INTO `drupal_flexifield_items` VALUES (3355);
INSERT INTO `drupal_flexifield_items` VALUES (3357);
INSERT INTO `drupal_flexifield_items` VALUES (3359);
INSERT INTO `drupal_flexifield_items` VALUES (3361);
INSERT INTO `drupal_flexifield_items` VALUES (3363);
INSERT INTO `drupal_flexifield_items` VALUES (3365);
INSERT INTO `drupal_flexifield_items` VALUES (3367);
INSERT INTO `drupal_flexifield_items` VALUES (3370);
INSERT INTO `drupal_flexifield_items` VALUES (3372);
INSERT INTO `drupal_flexifield_items` VALUES (3374);
INSERT INTO `drupal_flexifield_items` VALUES (3376);
INSERT INTO `drupal_flexifield_items` VALUES (3378);
INSERT INTO `drupal_flexifield_items` VALUES (3380);
INSERT INTO `drupal_flexifield_items` VALUES (3382);
INSERT INTO `drupal_flexifield_items` VALUES (3384);
INSERT INTO `drupal_flexifield_items` VALUES (3386);
INSERT INTO `drupal_flexifield_items` VALUES (3388);
INSERT INTO `drupal_flexifield_items` VALUES (3390);
INSERT INTO `drupal_flexifield_items` VALUES (3392);
INSERT INTO `drupal_flexifield_items` VALUES (3394);
INSERT INTO `drupal_flexifield_items` VALUES (3396);
INSERT INTO `drupal_flexifield_items` VALUES (3398);
INSERT INTO `drupal_flexifield_items` VALUES (3400);
INSERT INTO `drupal_flexifield_items` VALUES (3402);
INSERT INTO `drupal_flexifield_items` VALUES (3404);
INSERT INTO `drupal_flexifield_items` VALUES (3406);
/*!40000 ALTER TABLE `drupal_flexifield_items` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

