
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Not dumping tablespaces as no INFORMATION_SCHEMA.FILES table on this server
--
DROP TABLE IF EXISTS `drupal_term_data`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `drupal_term_data` (
  `tid` int(10) unsigned NOT NULL auto_increment,
  `vid` int(10) unsigned NOT NULL default '0',
  `name` varchar(255) NOT NULL default '',
  `description` longtext,
  `weight` tinyint(4) NOT NULL default '0',
  `language` varchar(12) NOT NULL default '',
  `trid` int(11) NOT NULL default '0',
  PRIMARY KEY  (`tid`),
  KEY `taxonomy_tree` (`vid`,`weight`,`name`),
  KEY `vid_name` (`vid`,`name`)
) ENGINE=MyISAM AUTO_INCREMENT=223 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `drupal_term_data` WRITE;
/*!40000 ALTER TABLE `drupal_term_data` DISABLE KEYS */;
INSERT INTO `drupal_term_data` VALUES (1,1,'DNS','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (2,1,'WWW','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (91,8,'Newsletter SKND','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (5,1,'LDAP','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (66,3,'Jak korzystać z forum','Dział dla wszystkich członków Cognitis, którzy jeszcze nie wiedzą jak poruszać się po forum ',28,'pl',0);
INSERT INTO `drupal_term_data` VALUES (64,3,'Humor','Trochę śmiechu nikomu nie zaszkodzi :)',26,'pl',0);
INSERT INTO `drupal_term_data` VALUES (65,3,'Imprezy','Informacje o tym kiedy, gdzie i jak się bawimy',27,'pl',0);
INSERT INTO `drupal_term_data` VALUES (63,3,'Potrzebna Pomoc','Prośby o pomoc wszelakiej postaci',25,'pl',0);
INSERT INTO `drupal_term_data` VALUES (56,3,'Zarząd','Zarząd Cognitis',7,'pl',0);
INSERT INTO `drupal_term_data` VALUES (57,3,'Projekty Cognitis','Informacje na temat realizowanych projektów Stowarzyszenia',6,'pl',0);
INSERT INTO `drupal_term_data` VALUES (58,3,'Rekrutacja','Wątki dotyczące działalności Zespołu ds. Rekrutacji',11,'pl',0);
INSERT INTO `drupal_term_data` VALUES (59,3,'ALUMNI Cognitis','Wątki dotyczące działalności Zespołu ds. ALUMNI Cognitis',16,'pl',0);
INSERT INTO `drupal_term_data` VALUES (60,3,'Innowacje','Wątki dotyczące działalności Zespołu ds. Innowacji',20,'pl',0);
INSERT INTO `drupal_term_data` VALUES (222,3,'Sprawy bieżące',' ',0,'pl',0);
INSERT INTO `drupal_term_data` VALUES (62,3,'Open Discussions','Dyskusje na wszelkie tematy',24,'pl',0);
INSERT INTO `drupal_term_data` VALUES (54,3,'Granty','Wątki dotyczące działalności Zespołu ds. Grantów',19,'pl',0);
INSERT INTO `drupal_term_data` VALUES (55,3,'Zarządzanie Jakością','Uwagi odnośnie jakości, krytyka, pochwały itd.',13,'pl',0);
INSERT INTO `drupal_term_data` VALUES (51,3,'Finanse','Wątki dotyczące działalności Zespołu ds. Finansów',12,'pl',0);
INSERT INTO `drupal_term_data` VALUES (52,3,'Marketing','Wątki dotyczące działalności Zespołu ds. Marketingu',17,'pl',0);
INSERT INTO `drupal_term_data` VALUES (53,3,'Integracja','Wątki dotyczące działalności Zespołu ds. Integracji',15,'pl',0);
INSERT INTO `drupal_term_data` VALUES (50,3,'Kontakty Zewnętrzne','Wątki dotyczące działalności Zespołu ds. Kontaktów Zewnętrznych',10,'pl',0);
INSERT INTO `drupal_term_data` VALUES (49,3,'Rozwój','Wątki dotyczące działalności Zespołu ds. Rozwoju',9,'pl',0);
INSERT INTO `drupal_term_data` VALUES (45,3,'Konkursy','Informacje o rozmaitych konkursach',3,'pl',0);
INSERT INTO `drupal_term_data` VALUES (47,3,'IT','Wątki dotyczące działalności Zespołu ds. IT',14,'pl',0);
INSERT INTO `drupal_term_data` VALUES (48,3,'Public Relations','Wątki dotyczące działalności Zespołu ds. Public Relations',18,'pl',0);
INSERT INTO `drupal_term_data` VALUES (43,3,'Praktyki','Oferty praktyk, staży, pracy itd.',2,'pl',0);
INSERT INTO `drupal_term_data` VALUES (44,3,'Wybory','Zadaj pytanie kandydatom!',5,'pl',0);
INSERT INTO `drupal_term_data` VALUES (41,3,'Ogłoszenia','Pilne ogłoszenia np. terminy spotkań',0,'pl',0);
INSERT INTO `drupal_term_data` VALUES (42,3,'Szkolenia','Terminy szkoleń',1,'pl',0);
INSERT INTO `drupal_term_data` VALUES (67,3,'Biuro','Informacje dotyczące biura Cognitis (m.in. rezerwacja biura na spotkania zespołów)',21,'pl',0);
INSERT INTO `drupal_term_data` VALUES (68,3,'SKaNDal','',22,'pl',0);
INSERT INTO `drupal_term_data` VALUES (69,3,'Członkowie za granicą','Cognitis ponad granicami.',29,'pl',0);
INSERT INTO `drupal_term_data` VALUES (70,3,'Pogotowie Rekrutacyjne','',23,'pl',0);
INSERT INTO `drupal_term_data` VALUES (71,3,'Archiwum','',7,'pl',0);
INSERT INTO `drupal_term_data` VALUES (72,3,'Bankowość Inwestycyjna','Tematy związane z projektem Bankowości Inwestycyjnej',31,'pl',0);
INSERT INTO `drupal_term_data` VALUES (73,3,'Kontakty z Uczelniami','Wątki dotyczące Zespołu ds. Kontaktów z Uczelniami',30,'pl',0);
INSERT INTO `drupal_term_data` VALUES (85,7,'Media','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (76,4,'Prezes','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (77,4,'Wiceprezes','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (78,4,'Koordynator','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (179,16,'ds. PR','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (90,7,'Consulting','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (82,5,'2007/2008','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (83,5,'2008/2009','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (84,5,'2009/2010','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (86,7,'Internet','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (87,7,'Press','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (88,7,'Radio','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (89,7,'Television','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (92,7,'Student','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (93,7,'Local','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (94,7,'Economic','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (95,7,'General','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (96,7,'Other','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (97,7,'Student','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (98,7,'Local','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (99,7,'Economic','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (100,7,'General','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (101,7,'Work and career','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (102,7,'Other','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (103,7,'Poznań','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (104,7,'Wrocław','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (105,7,'Warszawa','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (106,7,'General','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (107,7,'Other','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (108,7,'Poznań','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (109,7,'Wrocław','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (110,7,'Warszawa','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (111,7,'General','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (112,7,'Other','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (113,7,'Academy','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (114,7,'UE','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (115,7,'UAM','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (116,7,'PP','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (117,7,'Other','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (118,9,'Poznań','',-1,'',0);
INSERT INTO `drupal_term_data` VALUES (119,9,'University of Economics','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (120,9,'University of Technology','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (121,10,'Bachelor','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (122,10,'Master','',2,'',0);
INSERT INTO `drupal_term_data` VALUES (123,11,'None','',5,'',0);
INSERT INTO `drupal_term_data` VALUES (124,11,'Basic','',3,'',0);
INSERT INTO `drupal_term_data` VALUES (125,11,'Communicative','',4,'',0);
INSERT INTO `drupal_term_data` VALUES (126,11,'Intermediate','',2,'',0);
INSERT INTO `drupal_term_data` VALUES (127,11,'Advanced','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (128,11,'Fluent','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (129,10,'Engineer','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (134,9,'Recruitment','',-1,'',0);
INSERT INTO `drupal_term_data` VALUES (131,9,'Other','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (132,3,'Wrocław','Wątki dotyczące aktywności na uczelniach we Wrocławiu',8,'pl',0);
INSERT INTO `drupal_term_data` VALUES (133,9,'Adam Mickiewicz University','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (135,9,'Internal','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (136,9,'Poznań','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (137,9,'Wrocław','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (138,9,'Wrocław','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (139,9,'University of Economics','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (140,9,'University of Technology','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (141,9,'University of Wrocław','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (142,12,'Plakat Cognitis na Twojej uczelni','',4,'pl',0);
INSERT INTO `drupal_term_data` VALUES (143,12,'Stoisko Cognitis na Twojej uczelni','',6,'pl',0);
INSERT INTO `drupal_term_data` VALUES (144,12,'Ulotka Cognitis na Twojej uczelni','',8,'pl',0);
INSERT INTO `drupal_term_data` VALUES (145,12,'Spotkanie informacyjne na Twojej uczelni','',5,'pl',0);
INSERT INTO `drupal_term_data` VALUES (146,12,'Wizyta na wykładzie na Twojej uczelni','',9,'pl',0);
INSERT INTO `drupal_term_data` VALUES (147,12,'Wydarzenie organizowane przez Cognitis na Twojej uczelni','',11,'pl',0);
INSERT INTO `drupal_term_data` VALUES (148,12,'Wspólna prezentacja Cognitis i innych organizacji na Twojej uczelni.','',10,'pl',0);
INSERT INTO `drupal_term_data` VALUES (149,12,'Strona internetowa Twojej uczelni','',7,'pl',0);
INSERT INTO `drupal_term_data` VALUES (150,12,'Newsletter/ mailing Twojej uczelni','',3,'pl',0);
INSERT INTO `drupal_term_data` VALUES (151,12,'Członek Cognitis – jeśli chcesz, wpisz poniżej kto','',0,'pl',0);
INSERT INTO `drupal_term_data` VALUES (152,12,'Inna strona Internetowa - wpisz poniżej jaka','',1,'pl',0);
INSERT INTO `drupal_term_data` VALUES (153,12,'Inne źródło - wpisz poniżej jakie','',2,'pl',0);
INSERT INTO `drupal_term_data` VALUES (154,3,'Feedback nowej strony','Wszelkie uwagi dotyczące cognitis.pl',4,'pl',0);
INSERT INTO `drupal_term_data` VALUES (155,12,'(current)','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (156,12,'(archive)','',13,'',0);
INSERT INTO `drupal_term_data` VALUES (157,13,'(current)','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (158,10,'(current)','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (159,10,'(archive)','',4,'',0);
INSERT INTO `drupal_term_data` VALUES (160,13,'(archive)','',4,'',0);
INSERT INTO `drupal_term_data` VALUES (161,13,'Stationary','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (164,14,'I was the best in my group (class)','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (163,13,'Nonstationary','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (165,14,'I think I was one of the top 10%','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (166,14,'I think I was one of the top 25%','',2,'',0);
INSERT INTO `drupal_term_data` VALUES (167,14,'I think I was one of the top 50%','',3,'',0);
INSERT INTO `drupal_term_data` VALUES (168,14,'I focused on activities other than studying','',4,'',0);
INSERT INTO `drupal_term_data` VALUES (169,14,'(current)','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (170,14,'(archive)','',6,'',0);
INSERT INTO `drupal_term_data` VALUES (171,15,'(current)','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (172,15,'(archive)','',6,'',0);
INSERT INTO `drupal_term_data` VALUES (173,15,'I','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (174,15,'II','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (175,15,'III','',2,'',0);
INSERT INTO `drupal_term_data` VALUES (176,15,'IV','',3,'',0);
INSERT INTO `drupal_term_data` VALUES (177,15,'V','',4,'',0);
INSERT INTO `drupal_term_data` VALUES (178,8,'Newsletter Cognitis','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (180,16,'ds. IT','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (181,4,'p.o. Koordynatora','',3,'',0);
INSERT INTO `drupal_term_data` VALUES (182,4,'Zespoły','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (183,4,'Projekty','',5,'',0);
INSERT INTO `drupal_term_data` VALUES (184,4,'Koordynator','',2,'',0);
INSERT INTO `drupal_term_data` VALUES (185,4,'Firmy','',7,'',0);
INSERT INTO `drupal_term_data` VALUES (186,4,'Ambasador','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (187,17,'Wybór','',4,'',0);
INSERT INTO `drupal_term_data` VALUES (188,17,'Kandydat','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (189,17,'Wybrany','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (190,17,'Niewybrany','',2,'',0);
INSERT INTO `drupal_term_data` VALUES (191,17,'Absolutorium','',8,'',0);
INSERT INTO `drupal_term_data` VALUES (192,17,'Niegłosowane','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (193,17,'Udzielone','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (194,17,'Nieudzielone','',2,'',0);
INSERT INTO `drupal_term_data` VALUES (195,18,'Nadawane','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (196,18,'Kandydat','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (197,18,'Członek Nowy','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (198,18,'Aplikowane','',3,'',0);
INSERT INTO `drupal_term_data` VALUES (199,18,'Członek Zwyczajny','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (200,18,'Alumn','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (201,17,'Nadanie','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (202,17,'Niegłosowany','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (203,17,'Nadany','',1,'',0);
INSERT INTO `drupal_term_data` VALUES (204,17,'Nienadany','',2,'',0);
INSERT INTO `drupal_term_data` VALUES (205,16,'ds. Zarządzania Wiedzą','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (206,5,'2010/2011','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (207,16,'ds. Projektów','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (208,16,'ds. Finansów','',0,'',0);
INSERT INTO `drupal_term_data` VALUES (220,3,'Ogłoszenia','Te komunikaty mogą Cię zainteresować',4,'pl',0);
INSERT INTO `drupal_term_data` VALUES (219,3,'Zespoły Stałe','Śledź aktywność Zespołów Stałych',3,'pl',0);
INSERT INTO `drupal_term_data` VALUES (218,3,'Projekty','Zobacz, co słychać w Zespołach Projektowych',2,'pl',0);
INSERT INTO `drupal_term_data` VALUES (216,3,'Wybory','Zadaj pytanie kandydatom!',1,'pl',0);
INSERT INTO `drupal_term_data` VALUES (217,3,'Stowarzyszenie','Porozmawiaj o działalności Cognitis',0,'pl',0);
INSERT INTO `drupal_term_data` VALUES (221,3,'Offtopics','A tak z innej beczki...',5,'pl',0);
/*!40000 ALTER TABLE `drupal_term_data` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

