
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Not dumping tablespaces as no INFORMATION_SCHEMA.FILES table on this server
--
DROP TABLE IF EXISTS `drupal_users_roles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `drupal_users_roles` (
  `uid` int(10) unsigned NOT NULL default '0',
  `rid` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`uid`,`rid`),
  KEY `rid` (`rid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `drupal_users_roles` WRITE;
/*!40000 ALTER TABLE `drupal_users_roles` DISABLE KEYS */;
INSERT INTO `drupal_users_roles` VALUES (1,3);
INSERT INTO `drupal_users_roles` VALUES (133,5);
INSERT INTO `drupal_users_roles` VALUES (134,5);
INSERT INTO `drupal_users_roles` VALUES (135,5);
INSERT INTO `drupal_users_roles` VALUES (136,5);
INSERT INTO `drupal_users_roles` VALUES (137,5);
INSERT INTO `drupal_users_roles` VALUES (138,0);
INSERT INTO `drupal_users_roles` VALUES (139,0);
INSERT INTO `drupal_users_roles` VALUES (140,5);
INSERT INTO `drupal_users_roles` VALUES (141,0);
INSERT INTO `drupal_users_roles` VALUES (142,5);
INSERT INTO `drupal_users_roles` VALUES (143,5);
INSERT INTO `drupal_users_roles` VALUES (144,5);
INSERT INTO `drupal_users_roles` VALUES (145,5);
INSERT INTO `drupal_users_roles` VALUES (146,5);
INSERT INTO `drupal_users_roles` VALUES (146,8);
INSERT INTO `drupal_users_roles` VALUES (146,9);
INSERT INTO `drupal_users_roles` VALUES (146,10);
INSERT INTO `drupal_users_roles` VALUES (146,11);
INSERT INTO `drupal_users_roles` VALUES (147,5);
INSERT INTO `drupal_users_roles` VALUES (148,5);
INSERT INTO `drupal_users_roles` VALUES (149,0);
INSERT INTO `drupal_users_roles` VALUES (150,5);
INSERT INTO `drupal_users_roles` VALUES (151,5);
INSERT INTO `drupal_users_roles` VALUES (152,5);
INSERT INTO `drupal_users_roles` VALUES (153,0);
INSERT INTO `drupal_users_roles` VALUES (155,5);
INSERT INTO `drupal_users_roles` VALUES (156,5);
INSERT INTO `drupal_users_roles` VALUES (157,5);
INSERT INTO `drupal_users_roles` VALUES (158,5);
INSERT INTO `drupal_users_roles` VALUES (159,5);
INSERT INTO `drupal_users_roles` VALUES (160,0);
INSERT INTO `drupal_users_roles` VALUES (161,5);
INSERT INTO `drupal_users_roles` VALUES (161,9);
INSERT INTO `drupal_users_roles` VALUES (162,0);
INSERT INTO `drupal_users_roles` VALUES (163,5);
INSERT INTO `drupal_users_roles` VALUES (164,5);
INSERT INTO `drupal_users_roles` VALUES (165,5);
INSERT INTO `drupal_users_roles` VALUES (166,5);
INSERT INTO `drupal_users_roles` VALUES (167,5);
INSERT INTO `drupal_users_roles` VALUES (168,5);
INSERT INTO `drupal_users_roles` VALUES (169,0);
INSERT INTO `drupal_users_roles` VALUES (170,0);
INSERT INTO `drupal_users_roles` VALUES (171,0);
INSERT INTO `drupal_users_roles` VALUES (173,5);
INSERT INTO `drupal_users_roles` VALUES (175,5);
INSERT INTO `drupal_users_roles` VALUES (176,0);
INSERT INTO `drupal_users_roles` VALUES (177,0);
INSERT INTO `drupal_users_roles` VALUES (179,5);
INSERT INTO `drupal_users_roles` VALUES (180,5);
INSERT INTO `drupal_users_roles` VALUES (181,5);
INSERT INTO `drupal_users_roles` VALUES (181,9);
INSERT INTO `drupal_users_roles` VALUES (181,12);
INSERT INTO `drupal_users_roles` VALUES (181,13);
INSERT INTO `drupal_users_roles` VALUES (181,15);
INSERT INTO `drupal_users_roles` VALUES (181,19);
INSERT INTO `drupal_users_roles` VALUES (182,5);
INSERT INTO `drupal_users_roles` VALUES (183,5);
INSERT INTO `drupal_users_roles` VALUES (184,5);
INSERT INTO `drupal_users_roles` VALUES (185,0);
INSERT INTO `drupal_users_roles` VALUES (186,5);
INSERT INTO `drupal_users_roles` VALUES (187,0);
INSERT INTO `drupal_users_roles` VALUES (188,5);
INSERT INTO `drupal_users_roles` VALUES (188,19);
INSERT INTO `drupal_users_roles` VALUES (189,5);
INSERT INTO `drupal_users_roles` VALUES (190,0);
INSERT INTO `drupal_users_roles` VALUES (191,0);
INSERT INTO `drupal_users_roles` VALUES (192,0);
INSERT INTO `drupal_users_roles` VALUES (193,0);
INSERT INTO `drupal_users_roles` VALUES (194,5);
INSERT INTO `drupal_users_roles` VALUES (195,0);
INSERT INTO `drupal_users_roles` VALUES (196,5);
INSERT INTO `drupal_users_roles` VALUES (197,5);
INSERT INTO `drupal_users_roles` VALUES (198,5);
INSERT INTO `drupal_users_roles` VALUES (200,0);
INSERT INTO `drupal_users_roles` VALUES (201,5);
INSERT INTO `drupal_users_roles` VALUES (202,5);
INSERT INTO `drupal_users_roles` VALUES (203,5);
INSERT INTO `drupal_users_roles` VALUES (203,7);
INSERT INTO `drupal_users_roles` VALUES (204,0);
INSERT INTO `drupal_users_roles` VALUES (205,5);
INSERT INTO `drupal_users_roles` VALUES (206,5);
INSERT INTO `drupal_users_roles` VALUES (206,9);
INSERT INTO `drupal_users_roles` VALUES (206,10);
INSERT INTO `drupal_users_roles` VALUES (206,11);
INSERT INTO `drupal_users_roles` VALUES (206,19);
INSERT INTO `drupal_users_roles` VALUES (207,0);
INSERT INTO `drupal_users_roles` VALUES (208,5);
INSERT INTO `drupal_users_roles` VALUES (209,5);
INSERT INTO `drupal_users_roles` VALUES (210,0);
INSERT INTO `drupal_users_roles` VALUES (211,0);
INSERT INTO `drupal_users_roles` VALUES (212,0);
INSERT INTO `drupal_users_roles` VALUES (213,5);
INSERT INTO `drupal_users_roles` VALUES (214,5);
INSERT INTO `drupal_users_roles` VALUES (215,0);
INSERT INTO `drupal_users_roles` VALUES (216,0);
INSERT INTO `drupal_users_roles` VALUES (217,5);
INSERT INTO `drupal_users_roles` VALUES (217,9);
INSERT INTO `drupal_users_roles` VALUES (217,13);
INSERT INTO `drupal_users_roles` VALUES (217,14);
INSERT INTO `drupal_users_roles` VALUES (218,0);
INSERT INTO `drupal_users_roles` VALUES (219,0);
INSERT INTO `drupal_users_roles` VALUES (220,0);
INSERT INTO `drupal_users_roles` VALUES (221,0);
INSERT INTO `drupal_users_roles` VALUES (222,5);
INSERT INTO `drupal_users_roles` VALUES (224,0);
INSERT INTO `drupal_users_roles` VALUES (225,0);
INSERT INTO `drupal_users_roles` VALUES (227,5);
INSERT INTO `drupal_users_roles` VALUES (228,5);
INSERT INTO `drupal_users_roles` VALUES (230,5);
INSERT INTO `drupal_users_roles` VALUES (231,0);
INSERT INTO `drupal_users_roles` VALUES (232,5);
INSERT INTO `drupal_users_roles` VALUES (232,9);
INSERT INTO `drupal_users_roles` VALUES (233,5);
INSERT INTO `drupal_users_roles` VALUES (234,0);
INSERT INTO `drupal_users_roles` VALUES (235,0);
INSERT INTO `drupal_users_roles` VALUES (236,5);
INSERT INTO `drupal_users_roles` VALUES (237,5);
INSERT INTO `drupal_users_roles` VALUES (238,5);
INSERT INTO `drupal_users_roles` VALUES (239,5);
INSERT INTO `drupal_users_roles` VALUES (240,0);
INSERT INTO `drupal_users_roles` VALUES (241,5);
INSERT INTO `drupal_users_roles` VALUES (243,0);
INSERT INTO `drupal_users_roles` VALUES (244,0);
INSERT INTO `drupal_users_roles` VALUES (245,5);
INSERT INTO `drupal_users_roles` VALUES (245,8);
INSERT INTO `drupal_users_roles` VALUES (245,9);
INSERT INTO `drupal_users_roles` VALUES (246,5);
INSERT INTO `drupal_users_roles` VALUES (246,9);
INSERT INTO `drupal_users_roles` VALUES (246,12);
INSERT INTO `drupal_users_roles` VALUES (247,5);
INSERT INTO `drupal_users_roles` VALUES (248,0);
INSERT INTO `drupal_users_roles` VALUES (249,0);
INSERT INTO `drupal_users_roles` VALUES (250,0);
INSERT INTO `drupal_users_roles` VALUES (251,0);
INSERT INTO `drupal_users_roles` VALUES (253,0);
INSERT INTO `drupal_users_roles` VALUES (254,0);
INSERT INTO `drupal_users_roles` VALUES (255,0);
INSERT INTO `drupal_users_roles` VALUES (256,0);
INSERT INTO `drupal_users_roles` VALUES (257,0);
INSERT INTO `drupal_users_roles` VALUES (258,0);
INSERT INTO `drupal_users_roles` VALUES (259,0);
INSERT INTO `drupal_users_roles` VALUES (260,0);
INSERT INTO `drupal_users_roles` VALUES (261,5);
INSERT INTO `drupal_users_roles` VALUES (261,9);
INSERT INTO `drupal_users_roles` VALUES (262,5);
INSERT INTO `drupal_users_roles` VALUES (264,5);
INSERT INTO `drupal_users_roles` VALUES (265,5);
INSERT INTO `drupal_users_roles` VALUES (266,5);
INSERT INTO `drupal_users_roles` VALUES (267,5);
INSERT INTO `drupal_users_roles` VALUES (268,5);
INSERT INTO `drupal_users_roles` VALUES (269,5);
INSERT INTO `drupal_users_roles` VALUES (270,5);
INSERT INTO `drupal_users_roles` VALUES (270,17);
INSERT INTO `drupal_users_roles` VALUES (271,5);
INSERT INTO `drupal_users_roles` VALUES (272,5);
INSERT INTO `drupal_users_roles` VALUES (273,5);
INSERT INTO `drupal_users_roles` VALUES (274,5);
INSERT INTO `drupal_users_roles` VALUES (275,5);
INSERT INTO `drupal_users_roles` VALUES (276,5);
INSERT INTO `drupal_users_roles` VALUES (277,5);
INSERT INTO `drupal_users_roles` VALUES (278,5);
INSERT INTO `drupal_users_roles` VALUES (279,5);
INSERT INTO `drupal_users_roles` VALUES (280,5);
INSERT INTO `drupal_users_roles` VALUES (281,5);
INSERT INTO `drupal_users_roles` VALUES (282,5);
INSERT INTO `drupal_users_roles` VALUES (283,5);
INSERT INTO `drupal_users_roles` VALUES (284,5);
INSERT INTO `drupal_users_roles` VALUES (285,5);
INSERT INTO `drupal_users_roles` VALUES (286,5);
INSERT INTO `drupal_users_roles` VALUES (287,5);
INSERT INTO `drupal_users_roles` VALUES (288,5);
INSERT INTO `drupal_users_roles` VALUES (289,5);
INSERT INTO `drupal_users_roles` VALUES (290,5);
INSERT INTO `drupal_users_roles` VALUES (291,5);
INSERT INTO `drupal_users_roles` VALUES (292,5);
INSERT INTO `drupal_users_roles` VALUES (293,5);
INSERT INTO `drupal_users_roles` VALUES (294,5);
INSERT INTO `drupal_users_roles` VALUES (295,5);
INSERT INTO `drupal_users_roles` VALUES (296,5);
INSERT INTO `drupal_users_roles` VALUES (297,5);
INSERT INTO `drupal_users_roles` VALUES (298,5);
INSERT INTO `drupal_users_roles` VALUES (298,21);
INSERT INTO `drupal_users_roles` VALUES (299,5);
INSERT INTO `drupal_users_roles` VALUES (300,5);
INSERT INTO `drupal_users_roles` VALUES (301,5);
INSERT INTO `drupal_users_roles` VALUES (302,5);
INSERT INTO `drupal_users_roles` VALUES (303,5);
INSERT INTO `drupal_users_roles` VALUES (304,5);
INSERT INTO `drupal_users_roles` VALUES (305,5);
INSERT INTO `drupal_users_roles` VALUES (306,5);
INSERT INTO `drupal_users_roles` VALUES (307,5);
INSERT INTO `drupal_users_roles` VALUES (308,5);
INSERT INTO `drupal_users_roles` VALUES (309,5);
INSERT INTO `drupal_users_roles` VALUES (310,5);
INSERT INTO `drupal_users_roles` VALUES (311,5);
INSERT INTO `drupal_users_roles` VALUES (312,5);
INSERT INTO `drupal_users_roles` VALUES (313,5);
INSERT INTO `drupal_users_roles` VALUES (314,5);
INSERT INTO `drupal_users_roles` VALUES (315,5);
INSERT INTO `drupal_users_roles` VALUES (316,5);
INSERT INTO `drupal_users_roles` VALUES (317,5);
INSERT INTO `drupal_users_roles` VALUES (318,5);
INSERT INTO `drupal_users_roles` VALUES (318,12);
INSERT INTO `drupal_users_roles` VALUES (321,5);
INSERT INTO `drupal_users_roles` VALUES (322,5);
INSERT INTO `drupal_users_roles` VALUES (323,5);
INSERT INTO `drupal_users_roles` VALUES (324,5);
INSERT INTO `drupal_users_roles` VALUES (325,5);
INSERT INTO `drupal_users_roles` VALUES (325,21);
INSERT INTO `drupal_users_roles` VALUES (326,5);
/*!40000 ALTER TABLE `drupal_users_roles` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

