
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Not dumping tablespaces as no INFORMATION_SCHEMA.FILES table on this server
--
DROP TABLE IF EXISTS `drupal_phpbb2drupal_temp_user`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `drupal_phpbb2drupal_temp_user` (
  `user_id` mediumint(9) NOT NULL default '0',
  `uid` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `drupal_phpbb2drupal_temp_user` WRITE;
/*!40000 ALTER TABLE `drupal_phpbb2drupal_temp_user` DISABLE KEYS */;
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (2,1);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (3,133);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (4,134);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (5,135);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (6,136);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (7,137);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (9,138);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (10,139);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (11,140);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (12,141);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (14,142);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (15,143);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (16,144);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (17,145);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (19,146);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (20,147);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (21,148);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (22,149);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (24,150);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (26,151);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (27,152);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (28,153);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (29,154);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (31,155);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (34,156);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (37,157);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (38,158);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (39,159);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (40,160);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (41,161);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (42,162);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (43,163);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (44,164);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (45,165);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (46,166);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (49,167);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (50,168);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (52,169);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (53,170);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (54,171);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (59,172);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (61,173);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (62,174);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (63,175);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (65,176);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (66,177);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (67,178);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (68,179);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (70,180);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (71,181);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (75,182);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (77,183);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (79,184);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (80,185);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (82,186);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (85,187);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (87,188);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (89,189);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (90,190);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (91,191);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (92,192);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (93,193);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (96,194);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (98,195);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (99,196);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (101,197);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (105,198);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (107,199);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (109,200);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (110,201);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (111,202);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (113,203);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (114,204);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (116,205);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (117,206);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (118,207);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (119,208);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (120,209);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (121,210);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (123,211);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (125,212);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (128,213);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (129,214);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (133,215);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (134,216);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (137,217);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (138,218);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (140,219);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (141,220);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (145,221);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (146,222);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (147,223);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (149,224);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (150,225);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (152,226);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (153,227);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (154,228);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (155,229);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (156,230);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (157,231);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (158,232);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (159,233);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (160,234);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (161,235);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (162,236);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (163,237);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (164,238);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (165,239);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (166,240);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (167,241);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (168,242);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (169,243);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (170,244);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (171,245);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (172,246);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (173,247);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (174,248);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (175,249);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (176,250);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (177,251);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (178,252);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (179,253);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (180,254);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (181,255);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (182,256);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (183,257);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (184,258);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (185,259);
INSERT INTO `drupal_phpbb2drupal_temp_user` VALUES (186,260);
/*!40000 ALTER TABLE `drupal_phpbb2drupal_temp_user` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

