#!/bin/sh
TOOLS=../../src
TESTS="*.in"
TAG="init_best"

INITS="1 2 3" \
APPROXS="0" \
TIMEOUT="60" \
#$TOOLS/test2 "$TAG" "$TESTS"

INITS="1 2 3" \
APPROXS="1" \
TIMEOUT="60" \
#$TOOLS/test2 "$TAG" "$TESTS"

INITS="1 2 3" \
APPROXS="2" \
TIMEOUT="60" \
$TOOLS/test2 "$TAG" "$TESTS"
