#!/bin/sh
TOOLS=../../src

TAG="init_best"

TESTS="*.in"

INITS="1 2 3" \
APPROXS="0" \
TIMEOUT="60" \
#$TOOLS/test2 "$TAG" "$TESTS"

INITS="1 2 3" \
APPROXS="1" \
TIMEOUT="60" \
#$TOOLS/test2 "$TAG" "$TESTS"

INITS="1 2 3" \
APPROXS="2" \
TIMEOUT="60" \
#$TOOLS/test2 "$TAG" "$TESTS"

TESTS="24*.in"

INITS="3" \
APPROXS="1 2" \
TIMEOUT="60" \
$TOOLS/test2 "$TAG" "$TESTS"

