#!/bin/sh
DIR=`dirname $0`

for T in `mysql -h $1 -u $2 --password=$3 -N -B -e 'show tables' $4`; do
    echo $T;
    P=`echo $T | cut -d _ -f 1`;
    if [ $P = cache -o $P = sessions -o $P = watchdog ]; then
        mysqldump -h $1 -u $2 --password=$3 -d --skip-comments $4 $T > $DIR/sql/$T.sql;
    else
        mysqldump -h $1 -u $2 --password=$3 --skip-extended-insert --skip-comments $4 $T > $DIR/sql/$T.sql;
    fi
done