#!/bin/sh
DIR=`dirname $0`
mkdir -p $DIR/sql

for T in `mysql -h $1 -u $2 --password=$3 -N -B -e 'show tables' $4`; do
    M=`echo $T | cut -d _ -f 1`;
    P=`echo $T | cut -d _ -f 2`;

    if [ $M = moodle ]; then
      continue;
    fi

    echo $T;

    if [ $P = cache -o $P = sessions -o $P = watchdog -o $P = search ]; then
        mysqldump -h $1 -u $2 --password=$3 -d --skip-comments $4 $T > $DIR/sql/$T.sql;
    else
        mysqldump -h $1 -u $2 --password=$3 --skip-extended-insert --skip-comments $4 $T > $DIR/sql/$T.sql;
    fi
done