#!/bin/sh
TAG="sort i asp"
SMALL=" *-30-*.in"

TABUS="0" COUNTS="0" RESETS="1" DISTANCE="1 2 3 5" ../../src/test "$TAG" "$SMALL"
TABUS="5 15 25 50 75" COUNTS="50 100 200" RESETS="1" DISTANCE="1 2 3 5" ../../src/test "$TAG" "$SMALL"
