#!/bin/sh
TAG="sort i asp"
SMALL="10-*.in"

DISTANCE="1 2 3 5" DISTANCE2="distance" \
TABUS="10 50 100" TABUS2="tabus*tasks/100" \
CHANCES="50 100 200" CHANCES2="chances*tabus/100" \
RESETS="1" RESETS2="resets" \
../../src/test "$TAG" "$SMALL"
