<?php
// $Id: cacherouter.module,v 1.1.2.7 2010/01/29 15:17:29 andypost Exp $

/**
 * @file
 * Cache Router module helper.
 *
 * @author Steve Rude <steve@slantview.com>
 */

/**
 * Implementation of hook_user().
 *
 * When logged in you don't want to hit the page_fast_cache or else you will serve
 * a cached page to a logged in user.
 */
function cacherouter_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'login':
      setcookie('DRUPAL_UID', TRUE, time() + (60 * 60 * 24 * 30), '/');
      break;
    case 'logout':
      //Set in past to delete cookie
      setcookie('DRUPAL_UID', TRUE, time() - 3600, '/');
      break;
  }
}