#!/bin/sh
TOOLS=`dirname $0`


for offlines in `seq $OFFLINES`; do
for tasks in `seq $TASKS`; do
for repeat in `seq $REPEAT`; do
	
	offlines2=`echo "$offlines*$tasks/100" | bc | cut -d . -f 1`
	
	file="$offlines-$tasks-$repeat"
	if [ ! -f $file.in ]; then
		command="$TOOLS/generator $offlines2 $tasks > $file.in"
		echo $command >&2
		sh -c "$command 2>&-"
		echo tag,date,tabus,counts,resets,distance,cmax,time > $file.csv
	fi

done
done
done