#!/bin/sh
TABUS="10 3 45"
COUNTS="20 5 45"
RESETS="5 1 5"
TOOLS=`dirname $0`

target=$1
shift

echo -n file, > $target
head -1 $1 >> $target

for file in $*; do
	file=`basename $file .csv`
	echo "Processing $file..."
	grep ^[^t] $file.csv | sed s/^/$file,/ >> $target
done
