#!/bin/sh
target=$1
shift

headers=`head -1 $1`
echo tasks,offlines,repeat,$headers,cmax_min > $target


for file in $*; do
	file=`basename $file .csv`
	tasks=`echo $file | cut -d - -f 1`
	offlines=`echo $file | cut -d - -f 2`
	repeat=`echo $file | cut -d - -f 4`

	echo "Processing $file..." >&2

	cmax_min=`cat $file.csv | cut -d , -f 7 | sort | head -1`
	grep -v tag $file.csv | sed -r "s/^(.*)$/$tasks,$offlines,$repeat,\1,$cmax_min/" >> $target
done
