#!/bin/sh
target=$1
shift

echo -n tasks,offlines,repeat, > $target
head -1 $1 >> $target

for file in $*; do
	file=`basename $file .csv`
	tasks=`echo $file | cut -d - -f 1`
	offlines=`echo $file | cut -d - -f 2`
	repeat=`echo $file | cut -d - -f 4`

	echo "Processing $file..."
	grep ^[^t] $file.csv | sed -r "s/^/$tasks,$offlines,$repeat,/" >> $target
done
