#!/bin/sh
target=$1
shift

echo -n offlines,tasks,repeat, > $target
head -1 $1 >> $target

for file in $*; do
	file=`basename $file .csv`
	offlines=`echo $file | cut -d - -f 1`
	tasks=`echo $file | cut -d - -f 2`
	repeat=`echo $file | cut -d - -f 3`
		
	echo "Processing $file..."
	grep ^[^t] $file.csv | sed -r "s/^/$offlines,$tasks,$repeat,/" >> $target
done
