#!/bin/sh
#INITS="1 2 3"
#LIMITS="1 2 3"
#SETUPS="1 2"
#TIMEOUT="60"
TOOLS=`dirname $0`

tag=$1
shift

for file in $*; do
	file=`basename $file .in`
	tasks=`echo $file | cut -d - -f 1`
	offlines=`echo $file | cut -d - -f 2`

	for init in $INITS; do
	for limit in $LIMITS; do
	for setup in $SETUPS; do

		command="$TOOLS/branch $init $limit $setup <$file.in 2>$file.out 1>&-"
		#command=$tag
		echo $command >&2
		
		time=`/usr/bin/time -f %U sh -c "timeout $TIMEOUT $command" 2>&1`
		calls=`cat $file.out | cut -d , -f 1`
		date=`date +"%F %T"`
		
		echo $tag,$date,$init,$limit,$setup,$time,$calls >> $file.csv 
		
		rm $file.out
	done
	done
	done
done
