#!/bin/sh
REPEATS="1 1 5"
TASKS="20 1 20"
TABUS="5 1 25"
COUNTS="15 1 15"
RESETS="5 1 5"

total=0

for tasks in `seq $TASKS`; do
for repeat in `seq $REPEATS`; do
for tabus in `seq $TABUS`; do
for counts in `seq $COUNTS`; do
for resets in `seq $RESETS`; do
	total=`expr $total + 1`
done
done
done
done
done

echo total=$total >&2

echo tasks,tabus,counts,resets,cmax,time

for tasks in `seq $TASKS`; do
	for repeat in `seq $REPEATS`; do
		
		echo tasks=$tasks, repeat=$repeat >&2
		
		./generator $tasks $tasks > $tasks.in
	
		for tabus in `seq $TABUS`; do
		for counts in `seq $COUNTS`; do
		for resets in `seq $RESETS`; do
			tabu="./tabu $tabus $counts $resets < $tasks.in > $tasks.out 2>&-"
			time=`echo $tabu | /usr/bin/time -f %U sh 2>&1`
			cmax=`cat $tasks.out | ./cmax`
			
			echo $tasks,$tabus,$counts,$resets,$cmax,$time
		done
		done
		done
		
		rm $tasks.in
		rm $tasks.out
	done
done