#!/bin/sh
#INITS="1 1 3"
#APPROXS="1 1 3"
#TIMEOUT="60"
TOOLS=`dirname $0`

tag=$1
shift

for file in $*; do
	file=`basename $file .in`
	tasks=`echo $file | cut -d - -f 1`
	offlines=`echo $file | cut -d - -f 2`

	for init in $INITS; do
	for approx in $APPROXS; do

		command="$TOOLS/branch $init $approx < $file.in > $file.out"
		#command=$tag
		echo $command >&2
		
		time=`/usr/bin/time -f %U sh -c "timeout $TIMEOUT $command 2>&-" 2>&1`
		cmax=`cat $file.out | $TOOLS/cmax`
		date=`date +"%F %T"`
		
		echo $tag,$date,$init,$approx,$cmax,$time >> $file.csv 
		
		rm $file.out
	done
	done
done
