#!/bin/sh
TABUS="5 3 40"
COUNTS="10 5 40"
RESETS="3 1 3"
TOOLS=`dirname $0`

tag=$1
shift

for file in $*; do
	for tabus in `seq $TABUS`; do
	for counts in `seq $COUNTS`; do
	for resets in `seq $RESETS`; do
		rounds=`expr $rounds + 1`
	done
	done
	done
done

echo "Running $rounds times." >&2

for file in $*; do
	file=`basename $file .in`
	echo "Testing $file..." >&2
	
	for tabus in `seq $TABUS`; do
	for counts in `seq $COUNTS`; do
	for resets in `seq $RESETS`; do
		tabu="$TOOLS/tabu $tabus $counts $resets < $file.in > $file.out 2>&-"
		time=`echo $tabu | /usr/bin/time -f %U sh 2>&1`
		cmax=`cat $file.out | $TOOLS/cmax`
		date=`date +"%F %T"`
		
		echo $tag,$date,$tabus,$counts,$resets,$cmax,$time >> $file.csv 
		
		rm $file.out
	done
	done
	done
done
